#!/usr/bin/env bash
# Script that displays numbers 1 to 20:
#   "bad luck from China" the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
